### PR TITLE
docs: Add badges to readme

### PR DESCRIPTION
**Pull request by soda480**
Add relevant badges to readme

### CODE REVIEW

**Review by ernestojeda — DISMISSED** [review]
LGTM

**Review by bill-mahoney — DISMISSED** [review]

**Review by cjoyv — APPROVED** [review]
👍

**Comment by soda480** [comment]
@JamesKButcher is this repo deprecated? The DevOps team leveraged a script to add relevant badges (i.e. create PRs) for all non-archived & non-disabled repos in the EdgeXFoundry organization. I'm thinking this repo here is no longer active (it hasn't been built in quite some time) and thus does not require badges.

**Comment by JamesKButcher** [comment]
@soda480 yes correct - deprecated. In fact we should archive it. Thanks

**Comment by soda480** [comment]
closing PR - repo is deprecated

**Pull request closed without merging**
