### PR TITLE
Integrate with jenkins pipeline

### LINKED ISSUE #7: Automating performance test
Automating by Jenkins pipeline

### PR DESCRIPTION
**Pull request by cherrycl**
Signed-off-by: Cherry Wang <cherry@iotechsys.com>
fix #7 
- Grafana folder :  Only use when running on local grafana.
- Telegraf folder :  Start telegraf and edgeX services.
- Jmeter folder :  Run jmeter script.
- Jmeter > image folder : Use for build JMeter image. So far I built a image and put on [Docker Hub](https://cloud.docker.com/u/cherrycl/repository/docker/cherrycl/jmeter)  for temporary use.
- Jenkinsfile : Set 3 edgeX clients on it. For now, there are only 3 testcases it can be run on one edgeX client only. When more testcases is increased, second and third client can be used.

### CODE REVIEW

**Review by jamesrgregg — COMMENTED** [review]
@cherrycl I don't see that the remote cloud hosted endpoint is defined.  Is it your intention to spin this pipeline up on the EdgeX Jenkins build server and then launch separate containers that write performance data from the 3 slave containers to the AWS hosted InfluxDB?  I'm not sure what the goal is of this performance test.

**Comment by cherrycl** [comment]
@jamesrgregg I put host endpoints definition on yaml of jenkins job which I pushed on my repository and didn't open PR yet to ci-management. You can review it [here](https://github.com/cherrycl/ci-management/commit/5b0bddebeadf0cebfd0eaa2a0aadf7e6f6c2b8f4). I will open PR on ci-management after then PR of performance test repository is approved and merged.

**Comment by vishwassp** [comment]
@cherrycl  Could you please explain the stage ('before test')
Is this being assumed that SLAVE_EDGEX_1 is always non empty ?

**Comment by cherrycl** [comment]
Yes, SLAVE_EDGEX_1 couldn’t be empty. If it is empty, it means no edgeX endpoint existed.

**Comment by cherrycl** [comment]
For jenkins job, please refer [edgexfoundry/ci-management#338](https://github.com/edgexfoundry/ci-management/pull/338).

**Review by jamesrgregg — COMMENTED** [review]
Sorry.. I missed the comment above.. just need to test the job on Sandbox.

**Review by jamesrgregg — APPROVED** [review]
LGTM  - working job in Sandbox.

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
