### PR TITLE
Update performance test script document for docker-compose 

### LINKED ISSUE #35: Performance Test developing document has to be updated
Some files and information on the document are obsolete. The document has to review and update.

### PR DESCRIPTION
**Pull request by cherrycl**
Separate Grafana, InfluxDB and Telegraf to different docker-compose.

fix #35

### CODE REVIEW

**Comment by cherrycl** [comment]
@Walt-Intel I had updated the document, please help to review and let me know if any missing. Thank you.

**Comment by cloudxxx8** [comment]
@Walt-Intel are you able to review the document?  thanks

**Comment by Walt-Intel** [comment]
Looks good to me. I will give it a try on my machine later today.

**Review by Walt-Intel — COMMENTED** [review]
Looks good to me. I will give it a try on my machine later today.

**Review by Walt-Intel — APPROVED** [review]
Looks good to me.

**Review by cloudxxx8 — APPROVED** [review]
thanks! @Walt-Intel

**Comment by cherrycl** [comment]
Open new PR #41

**Pull request closed without merging**
