### PR TITLE
Core logging2

### PR DESCRIPTION
**Pull request by Walt-Intel**
Initial check-in of core logging performance test.

### CODE REVIEW

**Comment by cherrycl** [comment]
@Walt-Intel I have the following questions/comments.
1. Please remove "Property File Reader" which is only for developing. JMeter container which is used for automation doesn't install related the plugin.
2. What is that purpose to add all of testplans in one jmx file? Is this a standalone testcase?
3. If add the loglevel are required, what kind of logs you want to collect? I am thinking of the position of set log request.

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]
@Walt-Intel please separate your test from core-xxx
thanks

**Comment by cloudxxx8** [comment]
logging should be named support-logging

**Comment by Walt-Intel** [comment]
> @Walt-Intel I have the following questions/comments.
> 
> 1. Please remove "Property File Reader" which is only for developing. JMeter container which is used for automation doesn't install related the plugin.

Ok, I will update the test to remove the file reader.

> 2. What is that purpose to add all of testplans in one jmx file? Is this a standalone testcase?

I was planning on running the same test over a series of log level changes. My hope was to see a stair step in resource usage in Grafana. 

> 3. If add the loglevel are required, what kind of logs you want to collect? I am thinking of the position of set log request.

I want to set the log level in Consul in-between each iteration of the tests.  Right now the test case goes from setting the level to DEBUG, TRACE and then INFO

**Pull request closed without merging**
